export interface Meal {
  id: 'preworkout' | 'breakfast' | 'lunch' | 'snack' | 'dinner';
  time: string;
  name: string;
  description: string;
  protein: number;
  calories: number;
  carbs: number;
  fat: number;
}

export interface DayMealPlan {
  theme: string;
  totalProtein: number;
  totalCalories: number;
  totalCarbs: number;
  totalFat: number;
  meals: Meal[];
}

// 0=Sun, 1=Mon, ..., 6=Sat
export const mealPlans: Record<number, DayMealPlan> = {
  1: {
    theme: 'Chicken + Rice Day',
    totalProtein: 200,
    totalCalories: 2500,
    totalCarbs: 220,
    totalFat: 70,
    meals: [
      {
        id: 'preworkout',
        time: '6:30 AM',
        name: 'Pre-Workout',
        description: 'Protein shake 2 scoops whey + banana + creatine 5g + black coffee',
        protein: 48,
        calories: 360,
        carbs: 32,
        fat: 4,
      },
      {
        id: 'breakfast',
        time: '8:30 AM',
        name: 'Post-WO Breakfast',
        description: '6 oz chicken breast + 1 cup jasmine rice + 1 cup broccoli steamed',
        protein: 46,
        calories: 470,
        carbs: 54,
        fat: 5,
      },
      {
        id: 'lunch',
        time: '12:00 PM',
        name: 'Lunch',
        description: '8 oz chicken breast + 1.5 cups rice + mixed veggie stir-fry + low-sodium soy sauce',
        protein: 58,
        calories: 590,
        carbs: 65,
        fat: 7,
      },
      {
        id: 'snack',
        time: '3:30 PM',
        name: 'Afternoon Snack',
        description: '2 rice cakes + 3 tbsp almond butter + 1 apple sliced',
        protein: 10,
        calories: 390,
        carbs: 40,
        fat: 20,
      },
      {
        id: 'dinner',
        time: '7:00 PM',
        name: 'Dinner',
        description: '8 oz chicken thighs baked + 1 cup rice + mixed greens salad + 1 tbsp olive oil',
        protein: 52,
        calories: 570,
        carbs: 42,
        fat: 20,
      },
    ],
  },
  2: {
    theme: 'Salmon + Quinoa Day',
    totalProtein: 200,
    totalCalories: 2500,
    totalCarbs: 195,
    totalFat: 92,
    meals: [
      {
        id: 'preworkout',
        time: '6:30 AM',
        name: 'Pre-Workout',
        description: 'Protein shake + handful walnuts 1 oz + 1 apple + black coffee',
        protein: 38,
        calories: 440,
        carbs: 36,
        fat: 18,
      },
      {
        id: 'breakfast',
        time: '8:30 AM',
        name: 'Breakfast',
        description: '4 whole eggs scrambled + 3 oz smoked salmon + spinach sauté + 1 slice sourdough',
        protein: 44,
        calories: 500,
        carbs: 20,
        fat: 28,
      },
      {
        id: 'lunch',
        time: '12:00 PM',
        name: 'Lunch',
        description: '6 oz Atlantic salmon baked + 1 cup quinoa cooked + roasted asparagus + lemon',
        protein: 52,
        calories: 560,
        carbs: 48,
        fat: 20,
      },
      {
        id: 'snack',
        time: '3:30 PM',
        name: 'Afternoon Snack',
        description: '1 cup cottage cheese 2% + ½ cup pineapple + 1 tbsp ground flaxseed',
        protein: 28,
        calories: 280,
        carbs: 28,
        fat: 6,
      },
      {
        id: 'dinner',
        time: '7:00 PM',
        name: 'Dinner',
        description: '8 oz salmon fillet + 1.5 cups quinoa + cucumber tomato salad + ½ avocado + olive oil',
        protein: 56,
        calories: 610,
        carbs: 52,
        fat: 28,
      },
    ],
  },
  3: {
    theme: 'Ground Turkey + Potato Day',
    totalProtein: 200,
    totalCalories: 2500,
    totalCarbs: 230,
    totalFat: 68,
    meals: [
      {
        id: 'preworkout',
        time: '6:30 AM',
        name: 'Pre-Workout',
        description: 'Protein shake 2 scoops + ½ cup oats cooked + blueberries ½ cup',
        protein: 46,
        calories: 420,
        carbs: 50,
        fat: 6,
      },
      {
        id: 'breakfast',
        time: '8:30 AM',
        name: 'Breakfast',
        description: '6 oz ground turkey 93/7 + 1 medium baked potato + hot sauce + ketchup',
        protein: 44,
        calories: 480,
        carbs: 52,
        fat: 8,
      },
      {
        id: 'lunch',
        time: '12:00 PM',
        name: 'Lunch',
        description: '8 oz ground turkey + 1.5 cups mashed potato (Greek yogurt method) + green beans',
        protein: 54,
        calories: 570,
        carbs: 62,
        fat: 9,
      },
      {
        id: 'snack',
        time: '3:30 PM',
        name: 'Afternoon Snack',
        description: '3 string cheese sticks + 2 oz beef jerky + 1 cup grapes',
        protein: 24,
        calories: 310,
        carbs: 22,
        fat: 12,
      },
      {
        id: 'dinner',
        time: '7:00 PM',
        name: 'Dinner',
        description: 'Turkey meatballs 8 oz + roasted sweet potato chunks + broccoli + marinara sauce',
        protein: 52,
        calories: 570,
        carbs: 58,
        fat: 15,
      },
    ],
  },
  4: {
    theme: 'Steak + Rice Day',
    totalProtein: 210,
    totalCalories: 2600,
    totalCarbs: 210,
    totalFat: 92,
    meals: [
      {
        id: 'preworkout',
        time: '6:30 AM',
        name: 'Pre-Workout',
        description: 'Protein shake + banana + double espresso + creatine 5g',
        protein: 48,
        calories: 360,
        carbs: 32,
        fat: 4,
      },
      {
        id: 'breakfast',
        time: '8:30 AM',
        name: 'Breakfast',
        description: '5 whole eggs + 4 oz sirloin steak + 2 slices toast + 1 tbsp butter',
        protein: 60,
        calories: 650,
        carbs: 28,
        fat: 38,
      },
      {
        id: 'lunch',
        time: '12:00 PM',
        name: 'Lunch',
        description: '8 oz NY strip steak + 1.5 cups white rice + steamed broccoli + garlic butter',
        protein: 66,
        calories: 680,
        carbs: 58,
        fat: 26,
      },
      {
        id: 'snack',
        time: '3:30 PM',
        name: 'Afternoon Snack',
        description: '1 cup Greek yogurt + protein bar (Quest/RX) + 1 orange',
        protein: 30,
        calories: 380,
        carbs: 44,
        fat: 8,
      },
      {
        id: 'dinner',
        time: '7:00 PM',
        name: 'Dinner',
        description: '6 oz flank steak + 1 cup jasmine rice + chimichurri + side salad',
        protein: 48,
        calories: 540,
        carbs: 42,
        fat: 18,
      },
    ],
  },
  5: {
    theme: 'Tuna + Pasta Day',
    totalProtein: 195,
    totalCalories: 2550,
    totalCarbs: 265,
    totalFat: 65,
    meals: [
      {
        id: 'preworkout',
        time: '6:30 AM',
        name: 'Pre-Workout',
        description: 'Protein shake + 2 slices sourdough toast + 1 tbsp jam + black coffee',
        protein: 46,
        calories: 420,
        carbs: 48,
        fat: 5,
      },
      {
        id: 'breakfast',
        time: '8:30 AM',
        name: 'Breakfast',
        description: '6 oz canned tuna + 12 whole grain crackers + 1 tbsp light mayo + celery + apple',
        protein: 38,
        calories: 440,
        carbs: 46,
        fat: 8,
      },
      {
        id: 'lunch',
        time: '12:00 PM',
        name: 'Lunch',
        description: '2 cups penne + 5 oz tuna in marinara sauce + 2 tbsp parmesan',
        protein: 52,
        calories: 620,
        carbs: 82,
        fat: 10,
      },
      {
        id: 'snack',
        time: '3:30 PM',
        name: 'Afternoon Snack',
        description: '3 rice cakes + 2 tbsp peanut butter + 1 banana',
        protein: 12,
        calories: 360,
        carbs: 52,
        fat: 10,
      },
      {
        id: 'dinner',
        time: '7:00 PM',
        name: 'Dinner',
        description: '8 oz ahi tuna seared + 1.5 cups soba noodles + edamame ½ cup + sesame ginger sauce',
        protein: 58,
        calories: 600,
        carbs: 68,
        fat: 16,
      },
    ],
  },
  6: {
    theme: 'Flex Day',
    totalProtein: 200,
    totalCalories: 2500,
    totalCarbs: 220,
    totalFat: 75,
    meals: [
      {
        id: 'preworkout',
        time: '8:00 AM',
        name: 'Brunch',
        description: '5 eggs any style + 2 slices avocado toast + fresh fruit cup',
        protein: 40,
        calories: 560,
        carbs: 48,
        fat: 26,
      },
      {
        id: 'breakfast',
        time: '10:30 AM',
        name: 'Mid-Morning',
        description: 'Greek yogurt parfait 8 oz + granola ¼ cup + mixed berries + honey drizzle',
        protein: 22,
        calories: 370,
        carbs: 52,
        fat: 7,
      },
      {
        id: 'lunch',
        time: '1:00 PM',
        name: 'Lunch',
        description: 'Flex — choose high-protein option. Target: 50g+ protein, lean source',
        protein: 52,
        calories: 580,
        carbs: 52,
        fat: 18,
      },
      {
        id: 'snack',
        time: '4:00 PM',
        name: 'Snack',
        description: 'Protein shake or 1 cup cottage cheese + fruit of choice',
        protein: 36,
        calories: 310,
        carbs: 26,
        fat: 5,
      },
      {
        id: 'dinner',
        time: '7:30 PM',
        name: 'Family Dinner',
        description: 'Family dinner — make it work. Lean protein first, vegetables second, starch third',
        protein: 50,
        calories: 590,
        carbs: 50,
        fat: 20,
      },
    ],
  },
  0: {
    theme: 'Flex Day',
    totalProtein: 200,
    totalCalories: 2500,
    totalCarbs: 220,
    totalFat: 75,
    meals: [
      {
        id: 'preworkout',
        time: '8:00 AM',
        name: 'Brunch',
        description: '5 eggs any style + 2 slices avocado toast + fresh fruit cup',
        protein: 40,
        calories: 560,
        carbs: 48,
        fat: 26,
      },
      {
        id: 'breakfast',
        time: '10:30 AM',
        name: 'Mid-Morning',
        description: 'Greek yogurt parfait 8 oz + granola ¼ cup + mixed berries + honey drizzle',
        protein: 22,
        calories: 370,
        carbs: 52,
        fat: 7,
      },
      {
        id: 'lunch',
        time: '1:00 PM',
        name: 'Lunch',
        description: 'Flex — choose high-protein option. Target: 50g+ protein, lean source',
        protein: 52,
        calories: 580,
        carbs: 52,
        fat: 18,
      },
      {
        id: 'snack',
        time: '4:00 PM',
        name: 'Snack',
        description: 'Protein shake or 1 cup cottage cheese + fruit of choice',
        protein: 36,
        calories: 310,
        carbs: 26,
        fat: 5,
      },
      {
        id: 'dinner',
        time: '7:30 PM',
        name: 'Family Dinner',
        description: 'Family dinner — make it work. Lean protein first, vegetables second, starch third',
        protein: 50,
        calories: 590,
        carbs: 50,
        fat: 20,
      },
    ],
  },
};
